editor = '/opt/homebrew/bin/nvim'
cursor = '▇'
theme = "vivendi"
padding-x = 5
option-as-alt = 'left'

[window]
width = 1175 # 120 chars wide
height = 700 # 31 lines

[fonts]
family = "IntoneMono Nerd Font Mono"
size = 22

[fonts.regular]
weight = 500

[fonts.bold]
weight = 600

[fonts.italic]
weight = 500

[fonts.bold-italic]
weight = 600

[navigation]
mode = "Breadcrumb"
use-current-path = true

