---
- name: My MacOS Setup
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: Check if become is working
      ansible.builtin.command: whoami
      become: true
      register: become_check
      ignore_errors: true
      failed_when: false
      changed_when: false
    - name: Set variable for become usage
      ansible.builtin.set_fact:
        become_active: "{{ become_check.stdout | default('') == 'root' }}"
    - name: Import macOS settings tasks
      ansible.builtin.import_tasks: macos/main.ansible.yml
