###############################################################################
# Screen                                                                      #
###############################################################################

- name: Ask for password after sleep or screensaver
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: 1
    state: present

- name: Immediately ask for password after sleep or screensaver
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: int
    value: 0
    state: present

- name: Ensure the Downloads/ScreenCaptures directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Downloads/ScreenCaptures"
    state: directory
    mode: '0755'

- name: Save screenshots to the Downloads/ScreenCaptures
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "{{ ansible_env.HOME }}/Downloads/ScreenCaptures"
    state: present

- name: Disable shadow in screenshots
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: disable-shadow
    type: bool
    value: true
    state: present

- name: Save screenshots in PNG format
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: type
    type: string
    value: png
    state: present

- name: Enable subpixel font rendering on non-Apple LCDs
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleFontSmoothing
    type: int
    value: 2
    state: present
